// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3bb3df3f-cca5-49f8-b1e3-aa1ef926350b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_l0fS4Hphf",
    "aws_user_pools_web_client_id": "3nglqh6gcptlsv2mnqob3f9dm1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pgaupoerbvbjfaphg23rkev3qe.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yacibcz3b5ei3c3j7v3xly45vy"
};


export default awsmobile;
